# Generated by Django 4.2.10 on 2024-03-09 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_carseekuser_drivers_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('rental_rate_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='BaseApp.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='not_available_on',
            field=models.ManyToManyField(blank=True, related_name='cars_with_unavailable_dates', to='BaseApp.unavailabledate'),
        ),
        migrations.AddField(
            model_name='car',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
